services:

    flask:
        build:
            context: ./flask
            target: runtime
        image: bacharidocker/flask-product-api:v1.2.0

        ports:
          -  "5000:5000"

        depends_on:
            mysql:
                condition: service_healthy

        environment:
            DB_HOST: mysql
            DB_NAME: store
            DB_USER: root
            DB_PASSWORD: ${DB_PASSWORD}



    flask-test:
        build:
            context: ./flask
            target: test

        depends_on:
            mysql:
                condition: service_healthy

        environment:
            DB_HOST: mysql
            DB_NAME: store
            DB_USER: root
            DB_PASSWORD: ${DB_PASSWORD}
            TEST_DB_NAME: store_test


    mysql:
        image: mysql:8.0


        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}

        volumes:
           -  mysql-data:/var/lib/mysql
           -  ./mysql/init:/docker-entrypoint-initdb.d


        healthcheck:
           test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
           interval: 5s
           timeout: 5s
           retries: 20




volumes:
    mysql-data:
