name: CI


on:
    push:
    pull_request:


jobs:
    test:
        runs-on: ubuntu-latest


        steps:
          - name: Check out repository
            uses: actions/checkout@v6


          - name: Run tests
            run: docker compose run --rm flask-test

